
from openai import OpenAI
import os

# Importing the function to load environment variables
from dotenv import load_dotenv  

load_dotenv()

# Create an OpenAI client with your KRUTIM API KEY and endpoint
client = OpenAI(
    api_key=os.getenv('API_KEY'),
    base_url=os.getenv('BASE_URL')
)

# Create a chat completion request with the specified model and messages
completion = client.chat.completions.create(
  model="Meta-Llama-3-8B-Instruct",
  messages=[
    {"role": "system", "content": "You are a helpful assistant. Helps writing answers about Indian History."},
    {"role": "user", "content": "Please write an essay about Indian Independence."}
  ]
)

# Print the response generated by the model
print(completion.choices[0].message.content)